# Site settings
title: Discrete-2020
description: >
  Our discrete 2020 fall semester final project on the topic of exploring compression algorithms.
  We cover Discrete Cosine Transform, Lempel-Ziv-Welch and Arithmetic Coding.

baseurl: "/compression" # the subpath of your site, e.g. /blog/
url: "https://eito-fis.github.io" # the base hostname & protocol for your site

author:
  fullname: Eamon Ito-Fisher
  github: eito-fis

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown

